name: CI_action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: worksheet2/my-react-app

      - name: Add missing babel plugin
        run: npm install --save-dev @babel/plugin-proposal-private-property-in-object
        working-directory: worksheet2/my-react-app

      - name: Update App.test.tsx
        run: echo "export {};" >> src/App.test.tsx
        working-directory: worksheet2/my-react-app

      - name: Run the tests
        run: npm test -- --passWithNoTests
        working-directory: worksheet2/my-react-app

      - name: Build
        run: npm run build
        working-directory: worksheet2/my-react-app